# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=36)),
                ('name', models.CharField(max_length=128)),
                ('payload', models.TextField(blank=True, null=True)),
                ('queries', models.TextField(blank=True, null=True)),
                ('unlock_token', models.CharField(max_length=128)),
                ('status', models.IntegerField(choices=[(1, b'Pending'), (2, b'Running'), (3, b'Success'), (4, b'Failed')], default=1)),
                ('is_cron', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'mdm_device_command',
            },
        ),
        migrations.CreateModel(
            name='MDMDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udid', models.CharField(db_index=True, max_length=100, unique=True)),
                ('device_token', models.CharField(max_length=100)),
                ('push_magic', models.TextField(blank=True, null=True)),
                ('unlock_token', models.TextField(blank=True, null=True)),
                ('last_checkin', models.DateTimeField(null=True)),
                ('last_notification', models.DateTimeField(null=True)),
                ('name', models.CharField(blank=True, default=b'', max_length=128)),
                ('model', models.CharField(blank=True, default=b'', max_length=32)),
                ('serial_number', models.CharField(max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'db_table': 'mdm_device',
            },
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdm.MDMDevice'),
        ),
    ]
